before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenexr-dev
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install: python setup.py install
script: python test-exr.py
